### ISSUE TITLE
Add a wrapper around Chrome Storage API

### ISSUE THREAD

**Issue by maxxxxxdlp** [maxxxxxdlp/calendar-plus#9]
Integrate with Google Drive API so that extension can store it's data there

**Comment by maxxxxxdlp** [comment]
Actually, integrating with Google Drive is probably not needed because extensions already have access to storage API - https://developer.chrome.com/docs/extensions/reference/storage/

Extensions can sync storage data between all devices, or keep data local.

There is a quota limit on the storage, but if we run out, there is a `unlimitedStorage` permission we can request

**Comment by maxxxxxdlp** [comment]
@Durbatuluk1701  Integrating with Google Drive API won't be needed.

But, we will need a cache layer to save the computed summary of how much time the user spent on a particular event in a given week

**Comment by Durbatuluk1701** [comment]
@maxxxxxdlp Nice hopefully that should be simpler if I am understanding correctly?

**Comment by maxxxxxdlp** [comment]
Yes!

### Here is probably the best solution to this:
You could implement this using incremental synchronization - https://developers.google.com/calendar/api/guides/sync

I.e, our extension computes the stats for each day for every calendar for the last 4 years, and stores that locally.

Then, once an hour or once a day it recomputes the stats for the changed days using the calendar synchronization endpoint

### Another solution:
Fetch data one day at a time. Save computed events locally. Assume that past events do not change, and thus can be cached forever. Don't cache future events as they are likely to change.

Also, need to figure out some cache busting strategy (or at least a "clear cache" button in the UI)

**Comment by Durbatuluk1701** [comment]
Okay sounds good. I will look into implementing that this week. Sorry I didn't make much progress last week, I was extremely busy.

**Comment by Durbatuluk1701** [comment]
CLosed by #80
